apiVersion: v1
kind: PersistentVolume
metadata:
  name: clickhouse-pv
spec:
  capacity:
    storage: 200Mi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /mnt/data/clickhouse

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: clickhouse-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Mi

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: clickhouse
spec:
  serviceName: "clickhouse"
  replicas: 1
  selector:
    matchLabels:
      app: clickhouse
  template:
    metadata:
      labels:
        app: clickhouse
    spec:
      containers:
        - name: clickhouse
          image: yandex/clickhouse-server:latest
          ports:
            - name: tcp
              containerPort: 9000
            - name: http
              containerPort: 8123
          env:
            - name: CLICKHOUSE_USER
              valueFrom:
                configMapKeyRef:
                  name: clickhouse-config
                  key: CLICKHOUSE_USER
            - name: CLICKHOUSE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: clickhouse-secret
                  key: CLICKHOUSE_PASSWORD
            - name: CLICKHOUSE_DB
              valueFrom:
                configMapKeyRef:
                  name: clickhouse-config
                  key: CLICKHOUSE_DB
          volumeMounts:
            - name: clickhouse-data
              mountPath: /var/lib/clickhouse
      volumes:
        - name: clickhouse-data
          persistentVolumeClaim:
            claimName: clickhouse-pvc

---

apiVersion: v1
kind: Service
metadata:
  name: clickhouse-nodeport
spec:
  type: NodePort
  selector:
    app: clickhouse
  ports:
    - port: 8123
      targetPort: 8123
      protocol: TCP
      name: http
      nodePort: 30000

    - port: 9000
      targetPort: 9000
      protocol: TCP
      name: tcp
      nodePort: 30001

---

apiVersion: v1
kind: Service
metadata:
  name: clickhouse-clusterip
spec:
  type: ClusterIP
  selector:
    app: clickhouse
  ports:
    - port: 8123
      targetPort: 8123
      protocol: TCP
      name: http

    - port: 9000
      targetPort: 9000
      protocol: TCP
      name: tcp

---

apiVersion: batch/v1
kind: Job
metadata:
  name: clickhouse-migrations
spec:
  template:
    spec:
      containers:
        - name: goose-migrate
          image: xonest/clickhouse-migration:latest
          env:
            - name: CLICKHOUSE_DSN
              valueFrom:
                secretKeyRef:
                  name: clickhouse-secret
                  key: CLICKHOUSE_DSN
            - name: CLICKHOUSE_HOST
              valueFrom:
                configMapKeyRef:
                  name: clickhouse-config
                  key: CLICKHOUSE_HOST
            - name: CLICKHOUSE_PORT
              valueFrom:
                configMapKeyRef:
                  name: clickhouse-config
                  key: CLICKHOUSE_PORT
      restartPolicy: Never