apiVersion: v1
kind: Secret
metadata:
  name: clickhouse-secret
type: Opaque
data:
  CLICKHOUSE_PASSWORD: "ZmI5MjgyNzUtODc3MS00NGUyLWE3M2QtNzM5YWZhOTRkNzI1"
  CLICKHOUSE_DSN: "dGNwOi8vZGVmYXVsdDpmYjkyODI3NS04NzcxLTQ0ZTItYTczZC03MzlhZmE5NGQ3MjVAY2xpY2tob3VzZS1jbHVzdGVyaXA6OTAwMA=="

---

apiVersion: v1
kind: Secret
metadata:
  name: admin-panel-secret
type: Opaque
data:
  CLICKHOUSE_USER: "ZGVmYXVsdA=="
  CLICKHOUSE_DATABASE: "dGVsZWdyYW0="
  CLICKHOUSE_PASSWORD: "ZmI5MjgyNzUtODc3MS00NGUyLWE3M2QtNzM5YWZhOTRkNzI1"

---

apiVersion: v1
kind: Secret
metadata:
  name: statistics-sender-secret
type: Opaque
data:
  CLICKHOUSE_USER: "ZGVmYXVsdA=="
  CLICKHOUSE_DATABASE: "dGVsZWdyYW0="
  CLICKHOUSE_PASSWORD: "ZmI5MjgyNzUtODc3MS00NGUyLWE3M2QtNzM5YWZhOTRkNzI1"

---

apiVersion: v1
kind: Secret
metadata:
  name: telegram-bot-secret
type: Opaque
data:
  TELEGRAM_TOKEN: "NzA5NDE0NTY0MzpBQUVHVU15SWtuT3pMWXhLTUVCUHBsdC1aNDdDejh0NjQtaw=="
  CLICKHOUSE_USER: "ZGVmYXVsdA=="
  CLICKHOUSE_DATABASE: "dGVsZWdyYW0="
  CLICKHOUSE_PASSWORD: "ZmI5MjgyNzUtODc3MS00NGUyLWE3M2QtNzM5YWZhOTRkNzI1"
  CLICKHOUSE_PORT: "OTAwMA=="