ClickHouse:
  Host: "clickhouse"
  Port: "9000"
  Database: CLICKHOUSE_DATABASE
  User: CLICKHOUSE_USER
  Password: CLICKHOUSE_PASSWORD

Telegram:
  Token: TELEGRAM_TOKEN

Grpc:
  Host: "telegram-bot"
  Port: "50052"